service: cheetah

provider:
  name: google
  runtime: go111
  region: us-central1
  project: ${env:GCP_PROJECT}
  credentials: ${env:GCP_CREDENTIALS_FILE}

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - '**'
  include:
    - cheetah.go
    - go.mod
    - go.sum
    - cheetah.yaml

functions:
  cheetah:
    handler: Cheetah
    events:
      - http: http
    timeout: 60s
